"project_id": "507978"        #open project and go to Tools > API
"api_token": "21a7e20e574950cc7915137262e85db594e815a37dff900382560677981ad0d9acb8ed3bc657b8ab"          #open profile settings and go to API > New Token > create Token
"base_path": "/src/locales"

"files": [
  {
    "source": "/en.json",
    "translation": "/%two_letters_code%.json"
  }
]